name: codecov

on: [push, pull_request]

jobs:
  xcode-tests:
  name: "Tests"
    runs-on: macOS-latest

    strategy:
        platform: iOS
        include:
          - platform: iOS
            sdk: iphonesimulator
            destination: "name=iPhone 12"


    steps:
      - uses: actions/checkout@master
      - name: setup swift
        uses: actions/setup-swift@master
        with:
          swift-version: 5.5
          
     - name: Xcodebuild Action
       uses: sersoft-gmbh/xcodebuild-action@v1
        with:
          action: test
          project: NaZdrowie.xcodeproj
          scheme: NaZrowie
          destination: platform=macOS
          enable-code-coverage: true
          
      
    - name: upload codecov
      uses: codecov/codecov-action@v2
      
